[project]
name = "sequence-visualization-typer"
version = "0.1.0"
description = "A CLI tool to visualize sequences"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "nuitka>=2.5.7",
    "numpy>=2.2.0",
    "typer>=0.15.1",
]
